### ISSUE TITLE
Missing unique identifier for tasks

### ISSUE THREAD

**Issue by hugodemiglio** [formaweb/timetrello#4]
We need some unique identifier for tasks, may merging board/member/card IDs and generate a hash using these data. It is important that hash cannot be changed by user influence.

**Comment by caiotarifa** [comment]
Why not the `idAction`?

https://developers.trello.com/advanced-reference/action

**Comment by ronflima** [comment]
Will consider the Action Id as unique identifier. This identifier is generated and maintained by Trello itself.

**Comment by ronflima** [comment]
Implemented as required
